version: '3.8'

services:
  myapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - .:/app
    environment:
      ASPNETCORE_ENVIRONMENT: Development
